#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
#[ -f "$XINITRC" ] && alias startx='startx $XINITRC'
#[ -f "$MBSYNCRC" ] && alias mbsync='mbsync -c $MBSYNCRC'

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot vpm ; do
	alias $command="sudo $command"
done; unset command

netinfo ()
{
	echo "--------------- Network Information ---------------"
	/sbin/ifconfig | awk /'inet addr/ {print $2}'
	echo ""
	/sbin/ifconfig | awk /'Bcast/ {print $3}'
	echo ""
	/sbin/ifconfig | awk /'inet addr/ {print $4}'

	/sbin/ifconfig | awk /'HWaddr/ {print $4,$5}'
	echo "---------------------------------------------------"
}

se() {
	choice="$(find ~/.local/bin -mindepth 1 -printf '%P\n' | fzf)"
	[ -f "$HOME/.local/bin/$choice" ] && $EDITOR "$HOME/.local/bin/$choice"
	}

# tmux stuff
tmux () {
    case "$1" in
        "as")
            shift
            command tmux attach-session -t "$@"
            ;;
        "ks")
            shift
            command tmux kill-session -t "$@"
            ;;
        "ns")
            shift
            command tmux new-session -s "$@"
            ;;
        *)
            command tmux "$@"
            ;;
    esac
}

# Extract archives considering the file extension
extract() {
  case $1 in
    *.tar.gz|*.tgz) tar -xzf "$1";;
    *.tar.bz2|*.tbz2) tar -xjf "$1";;
    *.zip) unzip "$1";;
    *.rar) unrar x "$1";;
    *) echo "Unknown archive format";;
  esac
}

# ok
alias \
  top="btop" \
  fetch="fastfetch" \
  tw="typst watch --pdf-standard 1.5" \
  yta="yt-dlp -x -f 251 --embed-metadata --embed-thumbnail --no-playlist" \
  mylatex="latexmk -pdf -pvc -auxdir=temp -outdir=. main.tex"\
  pdf="zathura main.pdf"

#xbps
alias \
  xin="sudo xbps-install" \
  xre="sudo xbps-remove -R" \
  xcl="sudo xbps-remove -Oo"

# Verbosity
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	mkd="mkdir -pv" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	ip="ip -color=auto"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	e='$EDITOR' \
	v='$EDITOR' \
	z="zathura"

alias \
	ref='shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutenvrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc'
