#!/bin/sh
# shellcheck disable=SC2155
emulate sh -c 'source /etc/profile' # POSIX sh

# statusbar and binaries
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.local/bin/statusbar/:$PATH"

export PATH="$PATH:$(find ~/.local/bin -type d | paste -sd ':' -)"

unsetopt PROMPT_SP 2>/dev/null

# Default programs:
export IMGVIEWER="feh"
export EDITOR="nvim"
export TERMINAL="st"
export TERMINAL_PROG="st"
export BROWSER="firefox"

# fzf settings
export FZF_DEFAULT_OPTS=" \
  --border=rounded \
  --height=90% \
  --highlight-line
  --layout=reverse \
  --margin=1 \
  --padding=1 \
"
