# vim like movement

h seek -10
l seek 10

H seek -30
L seek 30

#j add volume -2
#k add volume 2

#Ctrl+h seek -60
#Ctrl+l seek 60

Space cycle pause
Enter cycle pause

, frame-back-step
. frame-step

- add speed -0.1
+ add speed 0.1
= set speed 1.0

J playlist-next
K playlist-prev

#[ add chapter -1
#] add chapter 1

n cycle sub
N cycle sub down

a cycle audio
f cycle fullscreen

zi add video-zoom 0.25
zo add video-zoom -0.25

i show-text "${filename}\n${time-pos} / ${duration}"

:q quit
ZQ quit
Q quit
