# Tmux conf

bind r source-file ~/.config/tmux/tmux.conf # reload config file

# remap prefix C-b to C-s
unbind C-b 
set-option -g prefix C-s
bind-key C-s send-prefix

# split panes using h and v
bind h split-window -h
bind v split-window -v
unbind '"'
unbind %

# options
set -g default-terminal "screen-256color"

set -g mouse on                             # clickable windows & panes, resiable panes
set-option -g allow-rename on               # Rename windows automatically
set-option -g display-time 4000             # By default, status msg disappears in the blink of an eye (750ms)
set-option -g display-panes-time 2000       # By default, pane number disappears in 1 s
set-option -g history-limit 99000           # maximum number of lines held in window history - crank it up from 2k default

set-window-option -g pane-base-index 1      # pane and window index will start with 1 instead of 0
set-option -g base-index 1
set-option -g renumber-windows on         

# space for session name
set -g status-left-length 100

# nvim tmux
# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator
vim_pattern='(\S+/)?g?\.?(view|l?n?vim?x?|fzf)(diff)?(-wrapped)?'
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +${vim_pattern}$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'
tmux_version='$(tmux -V | sed -En "s/^tmux ([0-9]+(.[0-9]+)?).*/\1/p")'
if-shell -b '[ "$(echo "$tmux_version < 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\'  'select-pane -l'"
if-shell -b '[ "$(echo "$tmux_version >= 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\\\'  'select-pane -l'"

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l
