#### config files for the z shell

SAVEHIST=99000000
HISTSIZE=99000000
HISTFILE="${XDG_CACHE_HOME:-$HOME/.cache}/zsh/history"

alias reloadzsh="source ~/.zshrc"

zmodload zsh/complist
autoload -Uz compinit && compinit
autoload -U colors && colors

setopt autocd               # type a dir to cd 
setopt auto_param_slash     # add a "/" instead of treadline on dirs
setopt globdots             # include dotfiles
setopt interactive_comments # allow comments in zshell
setopt nobeep
setopt multibyte
setopt numeric_glob_sort    
stty stop undef             # disables terminal freezing ctrl-s

# if not running, do not do anything
[ -z "$PS1" ] && return

#
..() { cd ..; ls }
...() { cd ../..; ls }
....() { cd ../../..; ls }
.....() { cd ../../../..; ls }

# vi mode
bindkey -v
export KEYTIMEOUT=1

# edit buffer
autoload -Uz edit-command-line
zle -N edit-command-line
bindkey '^E' edit-command-line

# basic tab completion
autoload -U compinit
zstyle ':completion:' menu select
zmodload zsh/complist
compinit
_comp_options+=(globdots) # include hidden files

# Use vim keys in tab complete menu:
#bindkey -M menuselect 'h' vi-backward-char
#bindkey -M menuselect 'k' vi-up-line-or-history
#bindkey -M menuselect 'l' vi-forward-char
#bindkey -M menuselect 'j' vi-down-line-or-history
#bindkey -v '^?' backward-delete-char

# evals
eval "$(zoxide init zsh)"
eval "$(starship init zsh)"

# source zsh config files
for x in \
  env \
  alias \
  functions \
  prompt \
  packages
do
  [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/zsh/$x.zsh" ] \
    && source "${XDG_CONFIG_HOME:-$HOME/.config}/zsh/$x.zsh"
done
unset x

# zsh plugins
for x in \
  zsh-autosuggestions/zsh-autosuggestions \
  zsh-syntax-highlighting/zsh-syntax-highlighting \
  zsh-history-substring-search/zsh-history-substring-search \
  zsh-vi-mode/zsh-vi-mode.plugin
do
  source "/usr/share/zsh/plugins/$x.zsh"
done
unset x
