#### Config file for the z shell, zoomer shell lmao
SAVEHIST=99000000
HISTSIZE=99000000
HISTFILE="${XDG_CACHE_HOME:-$HOME/.cache}/zsh/history"

alias reloadzsh="source ~/.zshrc"

zmodload zsh/complist
autoload -U compinit && compinit
autoload -U colors && colors
autoload -U tetris

setopt autocd               # type a dir to cd 
setopt auto_param_slash     # add a "/" instead of treadline on dirs
setopt globdots             # include dotfiles
setopt interactive_comments # allow comments in zshell 
stty stop undef             # disables terminal freezing ctrl-s

# if not running, do not do anything
[ -z "$PS1" ] && return

..() { cd ..; ls }
...() { cd ../..; ls }
....() { cd ../../..; ls }

# evals
eval "$(zoxide init zsh)"
eval "$(starship init zsh)"

# vi mode
bindkey -v
export KEYTIMEOUT=1

# basic tab completion
autoload -U compinit
zstyle ':completion:' menu select
zmodload zsh/complist
compinit
_comp_options+=(globdots) # include hidden files

# Use vim keys in tab complete menu:
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history
bindkey -v '^?' backward-delete-char

# fzf
fzfcleanfind() {
  clear | fd --type f --exclude .git --exclude dist | fzf
}
zle -N fzfcleanfind
bindkey '^F' fzfcleanfind

#[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc" ] && source "${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc"
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/zsh/env.zsh" ] && source "${XDG_CONFIG_HOME:-$HOME/.config}/zsh/env.zsh"
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/zsh/alias.zsh" ] && source "${XDG_CONFIG_HOME:-$HOME/.config}/zsh/alias.zsh"
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/zsh/functions.zsh" ] && source "${XDG_CONFIG_HOME:-$HOME/.config}/zsh/functions.zsh"
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/zsh/prompt.zsh" ] && source "${XDG_CONFIG_HOME:-$HOME/.config}/zsh/prompt.zsh"
#[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/zsh/nnn.zsh" ] && source "${XDG_CONFIG_HOME:-$HOME/.config}/zsh/nnn.zsh"

# Fish-like syntax highlighting and autosuggestions and history
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh
